//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RateController {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RateController.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string lgAbout {
            get {
                return ResourceManager.GetString("lgAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acres/Hr.
        /// </summary>
        internal static string lgAcresHr {
            get {
                return ResourceManager.GetString("lgAcresHr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Running.
        /// </summary>
        internal static string lgAlreadyRunning {
            get {
                return ResourceManager.GetString("lgAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud.
        /// </summary>
        internal static string lgBaud {
            get {
                return ResourceManager.GetString("lgBaud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cal Values.
        /// </summary>
        internal static string lgCalValues {
            get {
                return ResourceManager.GetString("lgCalValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string lgCancel {
            get {
                return ResourceManager.GetString("lgCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string lgClose {
            get {
                return ResourceManager.GetString("lgClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string lgConnect {
            get {
                return ResourceManager.GetString("lgConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string lgConnected {
            get {
                return ResourceManager.GetString("lgConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        internal static string lgController {
            get {
                return ResourceManager.GetString("lgController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage.
        /// </summary>
        internal static string lgCoverage {
            get {
                return ResourceManager.GetString("lgCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Rate ….
        /// </summary>
        internal static string lgCurrentRate {
            get {
                return ResourceManager.GetString("lgCurrentRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day/Night.
        /// </summary>
        internal static string lgDayNight {
            get {
                return ResourceManager.GetString("lgDayNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination IP.
        /// </summary>
        internal static string lgDestinationIP {
            get {
                return ResourceManager.GetString("lgDestinationIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        internal static string lgDiagnostics {
            get {
                return ResourceManager.GetString("lgDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string lgDisconnect {
            get {
                return ResourceManager.GetString("lgDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string lgDisconnected {
            get {
                return ResourceManager.GetString("lgDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Close.
        /// </summary>
        internal static string lgFastClose {
            get {
                return ResourceManager.GetString("lgFastClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft.
        /// </summary>
        internal static string lgft {
            get {
                return ResourceManager.GetString("lgft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hectares/Hr.
        /// </summary>
        internal static string lgHectares_Hr {
            get {
                return ResourceManager.GetString("lgHectares/Hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string lgHour {
            get {
                return ResourceManager.GetString("lgHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hr.
        /// </summary>
        internal static string lghr {
            get {
                return ResourceManager.GetString("lghr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant Rate ….
        /// </summary>
        internal static string lgInstantRate {
            get {
                return ResourceManager.GetString("lgInstantRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string lgIPAddress {
            get {
                return ResourceManager.GetString("lgIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPH.
        /// </summary>
        internal static string lgKPH {
            get {
                return ResourceManager.GetString("lgKPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string lgLoad {
            get {
                return ResourceManager.GetString("lgLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Defaults.
        /// </summary>
        internal static string lgLoad_Defaults {
            get {
                return ResourceManager.GetString("lgLoad Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoopBack UDP.
        /// </summary>
        internal static string lgLoopBackUDP {
            get {
                return ResourceManager.GetString("lgLoopBackUDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string lgMain {
            get {
                return ResourceManager.GetString("lgMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max PWM.
        /// </summary>
        internal static string lgMaxPWM {
            get {
                return ResourceManager.GetString("lgMaxPWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Cal Error.
        /// </summary>
        internal static string lgMeterCalError {
            get {
                return ResourceManager.GetString("lgMeterCalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min PWM.
        /// </summary>
        internal static string lgMinPWM {
            get {
                return ResourceManager.GetString("lgMinPWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string lgMinute {
            get {
                return ResourceManager.GetString("lgMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPH.
        /// </summary>
        internal static string lgMPH {
            get {
                return ResourceManager.GetString("lgMPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network UDP.
        /// </summary>
        internal static string lgNetwork_UDP {
            get {
                return ResourceManager.GetString("lgNetwork UDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Rate ….
        /// </summary>
        internal static string lgOverallRate {
            get {
                return ResourceManager.GetString("lgOverallRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string lgPort {
            get {
                return ResourceManager.GetString("lgPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Connected.
        /// </summary>
        internal static string lgPortConnected {
            get {
                return ResourceManager.GetString("lgPortConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Disconnected.
        /// </summary>
        internal static string lgPortDisconnected {
            get {
                return ResourceManager.GetString("lgPortDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string lgQuantity {
            get {
                return ResourceManager.GetString("lgQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Applied.
        /// </summary>
        internal static string lgQuantityApplied {
            get {
                return ResourceManager.GetString("lgQuantityApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Cal #.
        /// </summary>
        internal static string lgRateCal {
            get {
                return ResourceManager.GetString("lgRateCal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Set Error.
        /// </summary>
        internal static string lgRateSetError {
            get {
                return ResourceManager.GetString("lgRateSetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Nano.
        /// </summary>
        internal static string lgRealNano {
            get {
                return ResourceManager.GetString("lgRealNano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Port.
        /// </summary>
        internal static string lgReceivePort {
            get {
                return ResourceManager.GetString("lgReceivePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan Ports.
        /// </summary>
        internal static string lgRescanPorts {
            get {
                return ResourceManager.GetString("lgRescanPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Coverage.
        /// </summary>
        internal static string lgResetCoverage {
            get {
                return ResourceManager.GetString("lgResetCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Quantity.
        /// </summary>
        internal static string lgResetQuantity {
            get {
                return ResourceManager.GetString("lgResetQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Tank.
        /// </summary>
        internal static string lgResetTank {
            get {
                return ResourceManager.GetString("lgResetTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save  .
        /// </summary>
        internal static string lgSave {
            get {
                return ResourceManager.GetString("lgSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string lgSaveAs {
            get {
                return ResourceManager.GetString("lgSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Byte Hi.
        /// </summary>
        internal static string lgSectionByteHi {
            get {
                return ResourceManager.GetString("lgSectionByteHi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Byte Lo.
        /// </summary>
        internal static string lgSectionByteLo {
            get {
                return ResourceManager.GetString("lgSectionByteLo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Port.
        /// </summary>
        internal static string lgSendPort {
            get {
                return ResourceManager.GetString("lgSendPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Time.
        /// </summary>
        internal static string lgSendTime {
            get {
                return ResourceManager.GetString("lgSendTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Time Error.
        /// </summary>
        internal static string lgSendTimeError {
            get {
                return ResourceManager.GetString("lgSendTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string lgSettings {
            get {
                return ResourceManager.GetString("lgSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulate Flow.
        /// </summary>
        internal static string lgSimulateFlow {
            get {
                return ResourceManager.GetString("lgSimulateFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation Off.
        /// </summary>
        internal static string lgSimulationOff {
            get {
                return ResourceManager.GetString("lgSimulationOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string lgSpeed {
            get {
                return ResourceManager.GetString("lgSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string lgStandard {
            get {
                return ResourceManager.GetString("lgStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank Remaining.
        /// </summary>
        internal static string lgTank_Remaining {
            get {
                return ResourceManager.GetString("lgTank Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank Remaining Error.
        /// </summary>
        internal static string lgTankRemainError {
            get {
                return ResourceManager.GetString("lgTankRemainError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank Size.
        /// </summary>
        internal static string lgTankSize {
            get {
                return ResourceManager.GetString("lgTankSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank Size Error.
        /// </summary>
        internal static string lgTankSizeError {
            get {
                return ResourceManager.GetString("lgTankSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Rate.
        /// </summary>
        internal static string lgTargetRate {
            get {
                return ResourceManager.GetString("lgTargetRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDPLoopBack failed to start.
        /// </summary>
        internal static string lgUDPLoopBackFailed {
            get {
                return ResourceManager.GetString("lgUDPLoopBackFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDPnetwork failed to start.
        /// </summary>
        internal static string lgUDPnetworkFailed {
            get {
                return ResourceManager.GetString("lgUDPnetworkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgOpenGPS UDP must be on to receive..
        /// </summary>
        internal static string lgUDPnotice {
            get {
                return ResourceManager.GetString("lgUDPnotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPM Applied.
        /// </summary>
        internal static string lgUPMApplied {
            get {
                return ResourceManager.GetString("lgUPMApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPM Target.
        /// </summary>
        internal static string lgUPMTarget {
            get {
                return ResourceManager.GetString("lgUPMTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valve Type.
        /// </summary>
        internal static string lgValveType {
            get {
                return ResourceManager.GetString("lgValveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCN Error.
        /// </summary>
        internal static string lgVCNError {
            get {
                return ResourceManager.GetString("lgVCNError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCN is a 4 digit number. Backlash (1 short pulse to 9 long pulse), Speed (0 fast to 9 slow), Brake Point (0 5% to 9 90%) and Deadband (1 to 9 %).   ex: 743  no Backlash, 7 adjustment speed, 4 Brake Point at 40% error, deadband 3%.   Brake Point is the error % below which a slower adjustment speed is used.   Deadband is the error % below which no adjustment is made.  .
        /// </summary>
        internal static string lgVCNexplination {
            get {
                return ResourceManager.GetString("lgVCNexplination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Date.
        /// </summary>
        internal static string lgVersionDate {
            get {
                return ResourceManager.GetString("lgVersionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Nano.
        /// </summary>
        internal static string lgVirtualNano {
            get {
                return ResourceManager.GetString("lgVirtualNano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait Time.
        /// </summary>
        internal static string lgWaitTime {
            get {
                return ResourceManager.GetString("lgWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait Time Error.
        /// </summary>
        internal static string lgWaitTimeError {
            get {
                return ResourceManager.GetString("lgWaitTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Width.
        /// </summary>
        internal static string lgWorkingWidth {
            get {
                return ResourceManager.GetString("lgWorkingWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Width (FT).
        /// </summary>
        internal static string lgWorkingWidthFT {
            get {
                return ResourceManager.GetString("lgWorkingWidthFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Width (M).
        /// </summary>
        internal static string lgWorkingWidthM {
            get {
                return ResourceManager.GetString("lgWorkingWidthM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Rate.
        /// </summary>
        internal static string lgWorkRate {
            get {
                return ResourceManager.GetString("lgWorkRate", resourceCulture);
            }
        }
    }
}
