# iop_to_header.ps1 - Convert .iop file to C header for Teensy
#
# Usage:
#   .\iop_to_header.ps1 MyPool.iop
#   .\iop_to_header.ps1 MyPool.iop VTPoolData.h
#
# Generates a C header with the pool as a const uint8_t PROGMEM array.
# Object IDs in the .iop must match VTDefs.h for runtime updates to work.

param(
    [Parameter(Mandatory=$true, Position=0)]
    [string]$IopFile,

    [Parameter(Position=1)]
    [string]$OutputFile = "VTPoolData.h"
)

if (-not (Test-Path $IopFile)) {
    Write-Host "Error: File not found: $IopFile" -ForegroundColor Red
    exit 1
}

$data = [System.IO.File]::ReadAllBytes((Resolve-Path $IopFile))
$poolSize = $data.Length

Write-Host "IOP file: $IopFile"
Write-Host "Pool size: $poolSize bytes"

if ($poolSize -gt 1784) {
    Write-Host "WARNING: Pool is $poolSize bytes. Standard TP limit is 1785 bytes (including cmd byte)." -ForegroundColor Yellow
    Write-Host "         You may need Extended TP for pools this large." -ForegroundColor Yellow
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("// VTPoolData.h - Generated from .iop file")
[void]$sb.AppendLine("// Source: $(Split-Path $IopFile -Leaf)")
[void]$sb.AppendLine("// Size: $poolSize bytes")
[void]$sb.AppendLine("//")
[void]$sb.AppendLine("// Generated by iop_to_header.ps1")
[void]$sb.AppendLine("// Object IDs in this pool must match the IDs in VTDefs.h")
[void]$sb.AppendLine("// for runtime updates (Change Attribute, Change Numeric Value, etc.)")
[void]$sb.AppendLine("//")
[void]$sb.AppendLine("// To regenerate: .\iop_to_header.ps1 <your_pool.iop>")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("#ifndef VT_POOL_DATA_H")
[void]$sb.AppendLine("#define VT_POOL_DATA_H")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("#include <stdint.h>")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("#define IOP_POOL_SIZE $poolSize")
[void]$sb.AppendLine("")
[void]$sb.Append("const uint8_t iopPoolData[IOP_POOL_SIZE] PROGMEM = {")
[void]$sb.AppendLine("")

# Write 16 bytes per line
for ($i = 0; $i -lt $poolSize; $i += 16) {
    $end = [Math]::Min($i + 16, $poolSize)
    $hex = ($data[$i..($end-1)] | ForEach-Object { "0x{0:X2}" -f $_ }) -join ", "
    if ($end -lt $poolSize) {
        [void]$sb.AppendLine("    $hex,")
    } else {
        [void]$sb.AppendLine("    $hex")
    }
}

[void]$sb.AppendLine("};")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("#endif // VT_POOL_DATA_H")

[System.IO.File]::WriteAllText((Join-Path (Get-Location) $OutputFile), $sb.ToString())
Write-Host "Generated: $OutputFile" -ForegroundColor Green
