
// VTPool.ino - ISO 11783-6 VT Object Pool Loader
// Loads binary VT object pool from embedded .iop file (VTPoolData.h)
// generated by AgIsoTerminalDesigner and converted via iop_to_header.ps1

//=============================================================================
// VT Pool Buffer
//=============================================================================
#include "VTPoolData.h"

// Pool buffer size: TP handles up to 1785 bytes, ETP handles larger pools automatically
#define MAX_VT_POOL_SIZE          8192
uint8_t vtPoolBuffer[MAX_VT_POOL_SIZE];
uint16_t vtPoolSize = 0;

//=============================================================================
// IOP File Loading - loads pool from embedded .iop data (VTPoolData.h)
//=============================================================================

void VTPool_LoadIOP() {
    if (IOP_POOL_SIZE > MAX_VT_POOL_SIZE) {
        Serial.print("VT: IOP pool too large! ");
        Serial.print(IOP_POOL_SIZE);
        Serial.print(" > ");
        Serial.println(MAX_VT_POOL_SIZE);
        return;
    }
    memcpy(vtPoolBuffer, iopPoolData, IOP_POOL_SIZE);
    vtPoolSize = IOP_POOL_SIZE;
    Serial.print("VT: Loaded IOP pool, size=");
    Serial.println(vtPoolSize);
}

//=============================================================================
// Access Functions
//=============================================================================

const uint8_t* VTPool_GetBuffer() {
    return vtPoolBuffer;
}

uint16_t VTPool_GetSize() {
    return vtPoolSize;
}
