String GetPage2()
{
    String st = "<HTML>";
    st += "  <head>";
    st += "    <META content='text/html; charset=utf-8' http-equiv=Content-Type>";
    st += "    <meta name=vs_targetSchema content='HTML 4.0'>";
    st += "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
    st += "    <title>Rate Control</title>";
    st += "    <style>";
    st += "      html { font-family: Helvetica, Arial, sans-serif; display:inline-block; margin:0 auto; text-align:center; }";
    st += "      body { margin-top:50px; background-color:wheat; font-family:Arial, Helvetica, Sans-Serif; }";
    st += "      h1 { color:#444444; margin:50px auto 30px; }";
    st += "";
    st += "      table.center { margin-left:auto; margin-right:auto; border-collapse:collapse; table-layout:fixed; }";
    st += "      td.label-col { width:200px; text-align:left; padding:8px 12px; vertical-align:middle; }";
    st += "      td.input-col { width:320px; padding:8px 12px; vertical-align:middle; }";
    st += "";
    st += "      .control-width { width:320px; max-width:90%; margin:0 auto; box-sizing:border-box; }";
    st += "      .InputCell { display:block; width:100%; height:36px; box-sizing:border-box; text-align:center; font-size:18px; font-weight:700; padding:4px 6px; }";
    st += "";
    st += "      /* REVERTED: original purple gradient + shadows from your earlier CSS for button */";
    st += "      .button-72 {";
    st += "        align-items: center;";
    st += "        background-color: initial;";
    st += "        background-image: linear-gradient(rgba(179, 132, 201, .84), rgba(57, 31, 91, .84) 50%);";
    st += "        border-radius: 42px;";
    st += "        border-width: 0;";
    st += "        box-shadow: rgba(57, 31, 91, 0.24) 0 2px 2px, rgba(179, 132, 201, 0.4) 0 8px 12px;";
    st += "        color: #FFFFFF;";
    st += "        cursor: pointer;";
    st += "        display: inline-flex;";
    st += "        font-family: Quicksand, sans-serif;";
    st += "        font-size: 18px;";
    st += "        font-weight: 700;";
    st += "        justify-content: center;";
    st += "        letter-spacing: .04em;";
    st += "        line-height: 16px;";
    st += "        margin: 12px auto;";
    st += "        padding: 12px 18px;";
    st += "        text-align: center;";
    st += "        text-decoration: none;";
    st += "        text-shadow: rgba(255, 255, 255, 0.4) 0 0 4px, rgba(255, 255, 255, 0.2) 0 0 12px, rgba(57, 31, 91, 0.6) 1px 1px 4px, rgba(57, 31, 91, 0.32) 4px 4px 16px;";
    st += "        user-select: none;";
    st += "        -webkit-user-select: none;";
    st += "        touch-action: manipulation;";
    st += "        vertical-align: baseline;";
    st += "        width:320px; /* match control area */";
    st += "        max-width:90%;";
    st += "      }";
    st += "";
    st += "      a:link { font-size:150%; }";
    st += "";
    st += "      /* Left-aligned checkbox inside control area */";
    st += "      .checkbox-row { display:flex; align-items:center; height:44px; box-sizing:border-box; }";
    st += "      .checkbox-left { display:flex; align-items:center; justify-content:flex-start; }";
    st += "";
    st += "      /* Custom checkbox to match button: gradient background, shadow, rounded corners */";
    st += "      input[type=checkbox].styled {";
    st += "        -webkit-appearance: none;";
    st += "        appearance: none;";
    st += "        width:44px; height:44px; display:inline-block; position:relative; margin:0; padding:0; box-sizing:border-box;";
    st += "        border-radius:10px;";
    st += "        background-image: linear-gradient(rgba(179,132,201,.84), rgba(57,31,91,.84) 50%);";
    st += "        box-shadow: rgba(57,31,91,0.24) 0 2px 2px, rgba(179,132,201,0.4) 0 8px 12px;";
    st += "        cursor:pointer;";
    st += "        vertical-align:middle;";
    st += "        outline: none;";
    st += "        border: 1px solid rgba(57,31,91,0.25);";
    st += "      }";
    st += "";
    st += "      /* checkmark using an :after pseudo-element (correct orientation) */";
    st += "      input[type=checkbox].styled::after {";
    st += "        content: '';";
    st += "        position: absolute;";
    st += "        left: 50%; top: 50%;";
    st += "        width: 12px; height: 22px;";            // size of the mark stem+arm
    st += "        border-right: 4px solid white;";
    st += "        border-bottom: 4px solid white;";
    st += "        transform: translate(-50%,-60%) rotate(45deg) scale(0);";
    st += "        transform-origin: center;";
    st += "        transition: transform 0.12s ease-in-out;";
    st += "        border-radius:2px;";
    st += "      }";
    st += "      input[type=checkbox].styled:checked::after { transform: translate(-50%,-60%) rotate(45deg) scale(1); }";
    st += "";
    st += "      /* keep keyboard focus visible */";
    st += "      input[type=checkbox].styled:focus { box-shadow: 0 0 0 3px rgba(179,132,201,0.22); }";
    st += "";
    st += "      .label-normal { font-weight:normal; }";
    st += "    </style>";
    st += "  </head>";
    st += "";
    st += "  <BODY>";
    st += "    <h1 align=center>Wifi Network </h1>";
    st += "    <form id=FORM1 method=post action='/'>&nbsp;";
    st += "      <table class='center'>";
    st += "        <tr>";
    st += "          <td class='label-col'><span class='label-normal'>Use this Network</span></td>";
    st += "          <td class='input-col'>";
    st += "            <div class='control-width'>";
    st += "              <div class='checkbox-row'>";
    st += "                <div class='checkbox-left'>";
    st += "                  <label style='display:inline-flex; align-items:center; gap:8px; cursor:pointer;'>";
    st += "                    <input class='styled' type='checkbox' name='connect' value='1' " + String(ClientNetwork.WifiModeUseStation ? "checked" : "") + ">";
    st += "                  </label>";
    st += "                </div>";
    st += "              </div>";
    st += "            </div>";
    st += "          </td>";
    st += "        </tr>";
    st += "        <tr>";
    st += "          <td class='label-col'><span class='label-normal'>Network</span></td>";
    st += "          <td class='input-col'><div class='control-width'><input class='InputCell' id='ssid' size='20' name='prop1' value='" + String(ClientNetwork.SSID) + "'></div></td>";
    st += "        </tr>";
    st += "        <tr>";
    st += "          <td class='label-col'><span class='label-normal'>Password</span></td>";
    st += "          <td class='input-col'><div class='control-width'><input class='InputCell' id='pass' size='20' name='prop2' value='" + String(ClientNetwork.Password) + "'></div></td>";
    st += "        </tr>";
    st += "      </table>";
    st += "";
    st += "      <p><div class='control-width'><input class='button-72' id='submitBtn' type='submit' value='Save/Restart'></div></p>";
    st += "      <p> <a href='/page0'>Back</a> </p>";
    st += "    </form>";
    if (WiFi.isConnected())
    {
        st += "<p>Wifi Connected to " + String(ClientNetwork.SSID) + "</p>";
    }
    else
    {
        st += "<p>Wifi Not Connected</p>";
    }
    st += "</body>";
    st += "";
    st += "</HTML>";

    return st;
}
