String GetPageUpdate()
{
    String st =
        "<html>"
        "<head>"
        "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
        "<style>"
        "html {"
        "  font-family: Helvetica;"
        "  text-align: center;"
        "}"
        "body {"
        "  margin-top: 50px;"
        "  background-color: wheat;"
        "  font-size: 20px;"
        "}"
        ".button-72 {"
        "  align-items: center;"
        "  background-color: initial;"
        "  background-image: linear-gradient(rgba(179,132,201,.84), rgba(57,31,91,.84) 50%);"
        "  border-radius: 42px;"
        "  border-width: 0;"
        "  box-shadow: rgba(57,31,91,0.24) 0 2px 2px, rgba(179,132,201,0.4) 0 8px 12px;"
        "  color: #FFFFFF;"
        "  cursor: pointer;"
        "  display: flex;"
        "  flex-direction: column;"
        "  font-family: Quicksand, sans-serif;"
        "  font-size: 20px;"
        "  font-weight: 700;"
        "  justify-content: center;"
        "  letter-spacing: .04em;"
        "  margin: auto;"
        "  padding: 20px 20px;"
        "  text-align: center;"
        "  text-decoration: none;"
        "  text-shadow: rgba(255,255,255,0.4) 0 0 4px, rgba(255,255,255,0.2) 0 0 12px, rgba(57,31,91,0.6) 1px 1px 4px, rgba(57,31,91,0.32) 4px 4px 16px;"
        "  user-select: none;"
        "  width: 60%;"
        "}"
        ".container {"
        "  width: 90%;"
        "  max-width: 700px;"
        "  margin: auto;"
        "  background: white;"
        "  padding: 30px;"
        "  border-radius: 12px;"
        "  border: solid 2px #e0e0e0;"
        "}"
        ".filebox {"
        "  width: 100%;"
        "  font-size: 20px;"
        "  padding: 14px;"
        "  margin-bottom: 25px;"
        "}"
        ".progress-bg {"
        "  width: 100%;"
        "  background-color: #e0e0e0;"
        "  border-radius: 12px;"
        "  height: 32px;"
        "  margin-top: 20px;"
        "}"
        ".progress-bar {"
        "  width: 0%;"
        "  background-color: #2196F3;"
        "  height: 32px;"
        "  border-radius: 12px;"
        "  color: white;"
        "  text-align: center;"
        "  line-height: 32px;"
        "  font-size: 18px;"
        "}"
        "a:link { font-size: 150%; }"
        "</style>"
        "</head>"
        "<body>"
        "<div class='container'>"
        "<h1 style='color:#444;margin-bottom:30px;'>Firmware Update</h1>"
        "<form method='POST' action='#' enctype='multipart/form-data' id='upload-form'>"
        "<input class='filebox' type='file' name='update'>"
        "<button class='button-72' type='submit'>Upload &amp; Update</button>"
        "</form>"
        "<div class='progress-bg'>"
        "<div id='prg' class='progress-bar'>0%</div>"
        "</div>"
        "</div>"
        "<p><a href='/'>Back</a></p>"
        "<script>"
        "var prg = document.getElementById('prg');"
        "var form = document.getElementById('upload-form');"
        "form.addEventListener('submit', e=>{"
        "  e.preventDefault();"
        "  var data = new FormData(form);"
        "  var req = new XMLHttpRequest();"
        "  req.open('POST', '/update');"
        "  req.upload.addEventListener('progress', p=>{"
        "    if(p.lengthComputable){"
        "      let w = Math.round((p.loaded / p.total)*100) + '%';"
        "      prg.innerHTML = w;"
        "      prg.style.width = w;"
        "      if(w == '100%') prg.style.backgroundColor = '#04AA6D';"
        "    }"
        "  });"
        "  req.send(data);"
        "});"
        "</script>"
        "</body>"
        "</html>";
    return st;
}
