//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RateController {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RateController.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acres.
        /// </summary>
        internal static string lgAcres {
            get {
                return ResourceManager.GetString("lgAcres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acres/Hr.
        /// </summary>
        internal static string lgAcresHr {
            get {
                return ResourceManager.GetString("lgAcresHr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Running.
        /// </summary>
        internal static string lgAlreadyRunning {
            get {
                return ResourceManager.GetString("lgAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt. Rate (%).
        /// </summary>
        internal static string lgAltRate {
            get {
                return ResourceManager.GetString("lgAltRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Rate.
        /// </summary>
        internal static string lgBaseRate {
            get {
                return ResourceManager.GetString("lgBaseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boards.
        /// </summary>
        internal static string lgBoards {
            get {
                return ResourceManager.GetString("lgBoards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cal. Factor (Pulses/Unit).
        /// </summary>
        internal static string lgCalFactor {
            get {
                return ResourceManager.GetString("lgCalFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration steps:
        ///1. enter ground speed
        ///2. set calibration meter speed (rpm)
        /// * start with Master switch off
        /// * switch product on with the power button
        /// * enter initial base rate
        /// * enter initial Cal Factor
        /// * press start, RC attempts to adjust flow/rate to target
        /// * if successful meter speed is locked
        /// * press stop
        ///3. set Cal Factor (pulses/unit)
        /// * start with Master switch off
        /// * press start, turn Master switch on and let run to get an adequate sample amount
        /// * press stop and enter measured  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lgCalHelp {
            get {
                return ResourceManager.GetString("lgCalHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate.
        /// </summary>
        internal static string lgCalibrate {
            get {
                return ResourceManager.GetString("lgCalibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string lgCalProduct {
            get {
                return ResourceManager.GetString("lgCalProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration Speed.
        /// </summary>
        internal static string lgCalSpeed {
            get {
                return ResourceManager.GetString("lgCalSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string lgChannel {
            get {
                return ResourceManager.GetString("lgChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo Close.
        /// </summary>
        internal static string lgComboClose {
            get {
                return ResourceManager.GetString("lgComboClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo Timed.
        /// </summary>
        internal static string lgComboTimed {
            get {
                return ResourceManager.GetString("lgComboTimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comm.
        /// </summary>
        internal static string lgComm {
            get {
                return ResourceManager.GetString("lgComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comm Diagnostics.
        /// </summary>
        internal static string lgCommDiagnostics {
            get {
                return ResourceManager.GetString("lgCommDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        internal static string lgConfig {
            get {
                return ResourceManager.GetString("lgConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local IP.
        /// </summary>
        internal static string lgConfigIP {
            get {
                return ResourceManager.GetString("lgConfigIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string lgConnect {
            get {
                return ResourceManager.GetString("lgConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        internal static string lgControl {
            get {
                return ResourceManager.GetString("lgControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Type.
        /// </summary>
        internal static string lgControlType {
            get {
                return ResourceManager.GetString("lgControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts/Rev.
        /// </summary>
        internal static string lgCountsRev {
            get {
                return ResourceManager.GetString("lgCountsRev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage.
        /// </summary>
        internal static string lgCoverage {
            get {
                return ResourceManager.GetString("lgCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Rate ….
        /// </summary>
        internal static string lgCurrentRate {
            get {
                return ResourceManager.GetString("lgCurrentRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Product.
        /// </summary>
        internal static string lgDefaultProduct {
            get {
                return ResourceManager.GetString("lgDefaultProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density.
        /// </summary>
        internal static string lgDensity {
            get {
                return ResourceManager.GetString("lgDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derivative.
        /// </summary>
        internal static string lgDerivative {
            get {
                return ResourceManager.GetString("lgDerivative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string lgDescription {
            get {
                return ResourceManager.GetString("lgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        internal static string lgDiagnostics {
            get {
                return ResourceManager.GetString("lgDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string lgDisconnect {
            get {
                return ResourceManager.GetString("lgDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string lgDisplay {
            get {
                return ResourceManager.GetString("lgDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string lgEnd {
            get {
                return ResourceManager.GetString("lgEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =1.
        /// </summary>
        internal static string lgEqual {
            get {
                return ResourceManager.GetString("lgEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error %.
        /// </summary>
        internal static string lgError {
            get {
                return ResourceManager.GetString("lgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string lgExit {
            get {
                return ResourceManager.GetString("lgExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Amount.
        /// </summary>
        internal static string lgExpectedAmount {
            get {
                return ResourceManager.GetString("lgExpectedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan.
        /// </summary>
        internal static string lgFan {
            get {
                return ResourceManager.GetString("lgFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert Flow Control.
        /// </summary>
        internal static string lgFlowOnHigh {
            get {
                return ResourceManager.GetString("lgFlowOnHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo Stop.
        /// </summary>
        internal static string lgGeoStop {
            get {
                return ResourceManager.GetString("lgGeoStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hectares.
        /// </summary>
        internal static string lgHectares {
            get {
                return ResourceManager.GetString("lgHectares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hectares/Hr.
        /// </summary>
        internal static string lgHectares_Hr {
            get {
                return ResourceManager.GetString("lgHectares_Hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWM Maximum.
        /// </summary>
        internal static string lgHighMax {
            get {
                return ResourceManager.GetString("lgHighMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string lgHour {
            get {
                return ResourceManager.GetString("lgHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string lgHours {
            get {
                return ResourceManager.GetString("lgHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyd Down.
        /// </summary>
        internal static string lgHydDown {
            get {
                return ResourceManager.GetString("lgHydDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyd Up.
        /// </summary>
        internal static string lgHydUp {
            get {
                return ResourceManager.GetString("lgHydUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string lgID {
            get {
                return ResourceManager.GetString("lgID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant Rate ….
        /// </summary>
        internal static string lgInstantRate {
            get {
                return ResourceManager.GetString("lgInstantRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integral.
        /// </summary>
        internal static string lgIntegral {
            get {
                return ResourceManager.GetString("lgIntegral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert_Section.
        /// </summary>
        internal static string lgInvertSection {
            get {
                return ResourceManager.GetString("lgInvertSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPH.
        /// </summary>
        internal static string lgKPH {
            get {
                return ResourceManager.GetString("lgKPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lgLanguage {
            get {
                return ResourceManager.GetString("lgLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Screen.
        /// </summary>
        internal static string lgLargeScreen {
            get {
                return ResourceManager.GetString("lgLargeScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        internal static string lgMaster {
            get {
                return ResourceManager.GetString("lgMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Rate.
        /// </summary>
        internal static string lgMaxRate {
            get {
                return ResourceManager.GetString("lgMaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measured Amount.
        /// </summary>
        internal static string lgMeasuredAmount {
            get {
                return ResourceManager.GetString("lgMeasuredAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Set.
        /// </summary>
        internal static string lgMeterSet {
            get {
                return ResourceManager.GetString("lgMeterSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric Units.
        /// </summary>
        internal static string lgMetric {
            get {
                return ResourceManager.GetString("lgMetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWM Minimum.
        /// </summary>
        internal static string lgMinPWM {
            get {
                return ResourceManager.GetString("lgMinPWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Rate.
        /// </summary>
        internal static string lgMinRate {
            get {
                return ResourceManager.GetString("lgMinRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum UPM.
        /// </summary>
        internal static string lgMinUPM {
            get {
                return ResourceManager.GetString("lgMinUPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string lgMinute {
            get {
                return ResourceManager.GetString("lgMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string lgMinutes {
            get {
                return ResourceManager.GetString("lgMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        internal static string lgModule {
            get {
                return ResourceManager.GetString("lgModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module ID.
        /// </summary>
        internal static string lgModuleID {
            get {
                return ResourceManager.GetString("lgModuleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        internal static string lgModules {
            get {
                return ResourceManager.GetString("lgModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor.
        /// </summary>
        internal static string lgMotor {
            get {
                return ResourceManager.GetString("lgMotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor/Weight.
        /// </summary>
        internal static string lgMotorWeight {
            get {
                return ResourceManager.GetString("lgMotorWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPH.
        /// </summary>
        internal static string lgMPH {
            get {
                return ResourceManager.GetString("lgMPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string lgNetwork {
            get {
                return ResourceManager.GetString("lgNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string lgNew {
            get {
                return ResourceManager.GetString("lgNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string lgNone {
            get {
                return ResourceManager.GetString("lgNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Sections.
        /// </summary>
        internal static string lgNumSections {
            get {
                return ResourceManager.GetString("lgNumSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off-rate Alarm.
        /// </summary>
        internal static string lgOffRate {
            get {
                return ResourceManager.GetString("lgOffRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        internal static string lgOffset {
            get {
                return ResourceManager.GetString("lgOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Screen.
        /// </summary>
        internal static string lgOnScreen {
            get {
                return ResourceManager.GetString("lgOnScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Time.
        /// </summary>
        internal static string lgOnTime {
            get {
                return ResourceManager.GetString("lgOnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string lgOpen {
            get {
                return ResourceManager.GetString("lgOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string lgOptions {
            get {
                return ResourceManager.GetString("lgOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Rate ….
        /// </summary>
        internal static string lgOverallRate {
            get {
                return ResourceManager.GetString("lgOverallRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections Per Zone.
        /// </summary>
        internal static string lgPerZone {
            get {
                return ResourceManager.GetString("lgPerZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID Tuning Chart.
        /// </summary>
        internal static string lgPIDTune {
            get {
                return ResourceManager.GetString("lgPIDTune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pins.
        /// </summary>
        internal static string lgPins {
            get {
                return ResourceManager.GetString("lgPins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string lgPower {
            get {
                return ResourceManager.GetString("lgPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        internal static string lgPressure {
            get {
                return ResourceManager.GetString("lgPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primed Start.
        /// </summary>
        internal static string lgPrimedStart {
            get {
                return ResourceManager.GetString("lgPrimedStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string lgProduct {
            get {
                return ResourceManager.GetString("lgProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string lgProductName {
            get {
                return ResourceManager.GetString("lgProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/Fans.
        /// </summary>
        internal static string lgProducts {
            get {
                return ResourceManager.GetString("lgProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proportional.
        /// </summary>
        internal static string lgProportional {
            get {
                return ResourceManager.GetString("lgProportional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulses.
        /// </summary>
        internal static string lgPulses {
            get {
                return ResourceManager.GetString("lgPulses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWM Maximum.
        /// </summary>
        internal static string lgPWMmax {
            get {
                return ResourceManager.GetString("lgPWMmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWM Minimum.
        /// </summary>
        internal static string lgPWMmin {
            get {
                return ResourceManager.GetString("lgPWMmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string lgQuantity {
            get {
                return ResourceManager.GetString("lgQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Applied.
        /// </summary>
        internal static string lgQuantityApplied {
            get {
                return ResourceManager.GetString("lgQuantityApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string lgRate {
            get {
                return ResourceManager.GetString("lgRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Method.
        /// </summary>
        internal static string lgRateMethod {
            get {
                return ResourceManager.GetString("lgRateMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relay.
        /// </summary>
        internal static string lgRelay {
            get {
                return ResourceManager.GetString("lgRelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relay Control.
        /// </summary>
        internal static string lgRelayControl {
            get {
                return ResourceManager.GetString("lgRelayControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert Relay Control.
        /// </summary>
        internal static string lgRelayOnHigh {
            get {
                return ResourceManager.GetString("lgRelayOnHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relays.
        /// </summary>
        internal static string lgRelays {
            get {
                return ResourceManager.GetString("lgRelays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPM.
        /// </summary>
        internal static string lgRPM {
            get {
                return ResourceManager.GetString("lgRPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string lgSaveAs {
            get {
                return ResourceManager.GetString("lgSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string lgSeconds {
            get {
                return ResourceManager.GetString("lgSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string lgSection {
            get {
                return ResourceManager.GetString("lgSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section #.
        /// </summary>
        internal static string lgSectionNum {
            get {
                return ResourceManager.GetString("lgSectionNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections.
        /// </summary>
        internal static string lgSections {
            get {
                return ResourceManager.GetString("lgSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Subnet.
        /// </summary>
        internal static string lgSelectedSubnet {
            get {
                return ResourceManager.GetString("lgSelectedSubnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor.
        /// </summary>
        internal static string lgSensor {
            get {
                return ResourceManager.GetString("lgSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Count.
        /// </summary>
        internal static string lgSensorCount {
            get {
                return ResourceManager.GetString("lgSensorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Counts/Unit.
        /// </summary>
        internal static string lgSensorCounts {
            get {
                return ResourceManager.GetString("lgSensorCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor ID.
        /// </summary>
        internal static string lgSensorID {
            get {
                return ResourceManager.GetString("lgSensorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Location.
        /// </summary>
        internal static string lgSensorLocation {
            get {
                return ResourceManager.GetString("lgSensorLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Pressure.
        /// </summary>
        internal static string lgShowPressure {
            get {
                return ResourceManager.GetString("lgShowPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slave.
        /// </summary>
        internal static string lgSlave {
            get {
                return ResourceManager.GetString("lgSlave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string lgSpeed {
            get {
                return ResourceManager.GetString("lgSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard valve.
        /// </summary>
        internal static string lgStandard {
            get {
                return ResourceManager.GetString("lgStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Screen.
        /// </summary>
        internal static string lgStandardScreen {
            get {
                return ResourceManager.GetString("lgStandardScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string lgStart {
            get {
                return ResourceManager.GetString("lgStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank Starting Quantity.
        /// </summary>
        internal static string lgStartQuantity {
            get {
                return ResourceManager.GetString("lgStartQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subnet Address.
        /// </summary>
        internal static string lgSubnet {
            get {
                return ResourceManager.GetString("lgSubnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        internal static string lgSwitch {
            get {
                return ResourceManager.GetString("lgSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Delay.
        /// </summary>
        internal static string lgSwitchDelay {
            get {
                return ResourceManager.GetString("lgSwitchDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switches.
        /// </summary>
        internal static string lgSwitches {
            get {
                return ResourceManager.GetString("lgSwitches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Left.
        /// </summary>
        internal static string lgTank_Remaining {
            get {
                return ResourceManager.GetString("lgTank_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank Size.
        /// </summary>
        internal static string lgTankSize {
            get {
                return ResourceManager.GetString("lgTankSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Rate ....
        /// </summary>
        internal static string lgTargetRate {
            get {
                return ResourceManager.GetString("lgTargetRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Alt ....
        /// </summary>
        internal static string lgTargetRateAlt {
            get {
                return ResourceManager.GetString("lgTargetRateAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Pulse.
        /// </summary>
        internal static string lgTimeForMulti {
            get {
                return ResourceManager.GetString("lgTimeForMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Pulse.
        /// </summary>
        internal static string lgTimeForSingle {
            get {
                return ResourceManager.GetString("lgTimeForSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tram Left.
        /// </summary>
        internal static string lgTramLeft {
            get {
                return ResourceManager.GetString("lgTramLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tram Right.
        /// </summary>
        internal static string lgTramRight {
            get {
                return ResourceManager.GetString("lgTramRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        internal static string lgTransparent {
            get {
                return ResourceManager.GetString("lgTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string lgType {
            get {
                return ResourceManager.GetString("lgType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units/Volt.
        /// </summary>
        internal static string lgUnitsVolt {
            get {
                return ResourceManager.GetString("lgUnitsVolt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPM Applied.
        /// </summary>
        internal static string lgUPMApplied {
            get {
                return ResourceManager.GetString("lgUPMApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error %.
        /// </summary>
        internal static string lgUPMerror {
            get {
                return ResourceManager.GetString("lgUPMerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPM/PWM.
        /// </summary>
        internal static string lgUPMPWM {
            get {
                return ResourceManager.GetString("lgUPMPWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPM Target.
        /// </summary>
        internal static string lgUPMTarget {
            get {
                return ResourceManager.GetString("lgUPMTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Variable Rate.
        /// </summary>
        internal static string lgUseVR {
            get {
                return ResourceManager.GetString("lgUseVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string lgWidth {
            get {
                return ResourceManager.GetString("lgWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wifi Client.
        /// </summary>
        internal static string lgWifiClient {
            get {
                return ResourceManager.GetString("lgWifiClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wifi Port.
        /// </summary>
        internal static string lgWifiPort {
            get {
                return ResourceManager.GetString("lgWifiPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wifi Strength.
        /// </summary>
        internal static string lgWifiSignal {
            get {
                return ResourceManager.GetString("lgWifiSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Width (FT).
        /// </summary>
        internal static string lgWorkingWidthFT {
            get {
                return ResourceManager.GetString("lgWorkingWidthFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Width (M).
        /// </summary>
        internal static string lgWorkingWidthM {
            get {
                return ResourceManager.GetString("lgWorkingWidthM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Pin.
        /// </summary>
        internal static string lgWorkPin {
            get {
                return ResourceManager.GetString("lgWorkPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Switch.
        /// </summary>
        internal static string lgWorkSwitch {
            get {
                return ResourceManager.GetString("lgWorkSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        internal static string lgZone {
            get {
                return ResourceManager.GetString("lgZone", resourceCulture);
            }
        }
    }
}
