//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RateController {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RateController.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string lgAbout {
            get {
                return ResourceManager.GetString("lgAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acres.
        /// </summary>
        internal static string lgAcres {
            get {
                return ResourceManager.GetString("lgAcres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acres/Hr.
        /// </summary>
        internal static string lgAcresHr {
            get {
                return ResourceManager.GetString("lgAcresHr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Running.
        /// </summary>
        internal static string lgAlreadyRunning {
            get {
                return ResourceManager.GetString("lgAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt. Rate.
        /// </summary>
        internal static string lgAltRate {
            get {
                return ResourceManager.GetString("lgAltRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string lgAuto {
            get {
                return ResourceManager.GetString("lgAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Rate.
        /// </summary>
        internal static string lgBaseRate {
            get {
                return ResourceManager.GetString("lgBaseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brake Point.
        /// </summary>
        internal static string lgBrakePoint {
            get {
                return ResourceManager.GetString("lgBrakePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Rate Settings.
        /// </summary>
        internal static string lgCalCopy {
            get {
                return ResourceManager.GetString("lgCalCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string lgCalculate {
            get {
                return ResourceManager.GetString("lgCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate.
        /// </summary>
        internal static string lgCalibrate {
            get {
                return ResourceManager.GetString("lgCalibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cal Values.
        /// </summary>
        internal static string lgCalValues {
            get {
                return ResourceManager.GetString("lgCalValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string lgCancel {
            get {
                return ResourceManager.GetString("lgCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string lgClose {
            get {
                return ResourceManager.GetString("lgClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo Close.
        /// </summary>
        internal static string lgComboClose {
            get {
                return ResourceManager.GetString("lgComboClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comm.
        /// </summary>
        internal static string lgComm {
            get {
                return ResourceManager.GetString("lgComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string lgConnect {
            get {
                return ResourceManager.GetString("lgConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        internal static string lgControl {
            get {
                return ResourceManager.GetString("lgControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Type.
        /// </summary>
        internal static string lgControlType {
            get {
                return ResourceManager.GetString("lgControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts/Rev.
        /// </summary>
        internal static string lgCountsRev {
            get {
                return ResourceManager.GetString("lgCountsRev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage.
        /// </summary>
        internal static string lgCoverage {
            get {
                return ResourceManager.GetString("lgCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Rate ….
        /// </summary>
        internal static string lgCurrentRate {
            get {
                return ResourceManager.GetString("lgCurrentRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadband.
        /// </summary>
        internal static string lgDeadband {
            get {
                return ResourceManager.GetString("lgDeadband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string lgDescription {
            get {
                return ResourceManager.GetString("lgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination IP.
        /// </summary>
        internal static string lgDestinationIP {
            get {
                return ResourceManager.GetString("lgDestinationIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        internal static string lgDiagnostics {
            get {
                return ResourceManager.GetString("lgDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string lgDisconnect {
            get {
                return ResourceManager.GetString("lgDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =1.
        /// </summary>
        internal static string lgEqual {
            get {
                return ResourceManager.GetString("lgEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware.
        /// </summary>
        internal static string lgFirmware {
            get {
                return ResourceManager.GetString("lgFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hectares.
        /// </summary>
        internal static string lgHectares {
            get {
                return ResourceManager.GetString("lgHectares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hectares/Hr.
        /// </summary>
        internal static string lgHectares_Hr {
            get {
                return ResourceManager.GetString("lgHectares_Hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWM Maximum.
        /// </summary>
        internal static string lgHighMax {
            get {
                return ResourceManager.GetString("lgHighMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Hotspot.
        /// </summary>
        internal static string lgHotspot {
            get {
                return ResourceManager.GetString("lgHotspot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string lgHour {
            get {
                return ResourceManager.GetString("lgHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string lgHours {
            get {
                return ResourceManager.GetString("lgHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string lgID {
            get {
                return ResourceManager.GetString("lgID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inches.
        /// </summary>
        internal static string lgInches {
            get {
                return ResourceManager.GetString("lgInches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant Rate ….
        /// </summary>
        internal static string lgInstantRate {
            get {
                return ResourceManager.GetString("lgInstantRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integral Adjustment.
        /// </summary>
        internal static string lgIntegralAdjustment {
            get {
                return ResourceManager.GetString("lgIntegralAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert_Section.
        /// </summary>
        internal static string lgInvertSection {
            get {
                return ResourceManager.GetString("lgInvertSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPH.
        /// </summary>
        internal static string lgKPH {
            get {
                return ResourceManager.GetString("lgKPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lgLanguage {
            get {
                return ResourceManager.GetString("lgLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string lgLoad {
            get {
                return ResourceManager.GetString("lgLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Defaults.
        /// </summary>
        internal static string lgLoad_Defaults {
            get {
                return ResourceManager.GetString("lgLoad_Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethernet IP.
        /// </summary>
        internal static string lgLocalIP {
            get {
                return ResourceManager.GetString("lgLocalIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWM Low Max.
        /// </summary>
        internal static string lgLowMax {
            get {
                return ResourceManager.GetString("lgLowMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        internal static string lgMaster {
            get {
                return ResourceManager.GetString("lgMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Off.
        /// </summary>
        internal static string lgMasterOff {
            get {
                return ResourceManager.GetString("lgMasterOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master On.
        /// </summary>
        internal static string lgMasterOn {
            get {
                return ResourceManager.GetString("lgMasterOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric Units.
        /// </summary>
        internal static string lgMetric {
            get {
                return ResourceManager.GetString("lgMetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWM Minimum.
        /// </summary>
        internal static string lgMinPWM {
            get {
                return ResourceManager.GetString("lgMinPWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum UPM.
        /// </summary>
        internal static string lgMinUPM {
            get {
                return ResourceManager.GetString("lgMinUPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string lgMinute {
            get {
                return ResourceManager.GetString("lgMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string lgMinutes {
            get {
                return ResourceManager.GetString("lgMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        internal static string lgModule {
            get {
                return ResourceManager.GetString("lgModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module ID.
        /// </summary>
        internal static string lgModuleID {
            get {
                return ResourceManager.GetString("lgModuleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor.
        /// </summary>
        internal static string lgMotor {
            get {
                return ResourceManager.GetString("lgMotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor/Weight.
        /// </summary>
        internal static string lgMotorWeight {
            get {
                return ResourceManager.GetString("lgMotorWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPH.
        /// </summary>
        internal static string lgMPH {
            get {
                return ResourceManager.GetString("lgMPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string lgNetwork {
            get {
                return ResourceManager.GetString("lgNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Connections.
        /// </summary>
        internal static string lgNetworkConnections {
            get {
                return ResourceManager.GetString("lgNetworkConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string lgNew {
            get {
                return ResourceManager.GetString("lgNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Sections.
        /// </summary>
        internal static string lgNumSections {
            get {
                return ResourceManager.GetString("lgNumSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off-rate Alarm.
        /// </summary>
        internal static string lgOffRate {
            get {
                return ResourceManager.GetString("lgOffRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        internal static string lgOffset {
            get {
                return ResourceManager.GetString("lgOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string lgOpen {
            get {
                return ResourceManager.GetString("lgOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string lgOptions {
            get {
                return ResourceManager.GetString("lgOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Rate ….
        /// </summary>
        internal static string lgOverallRate {
            get {
                return ResourceManager.GetString("lgOverallRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string lgPassword {
            get {
                return ResourceManager.GetString("lgPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCB Config.
        /// </summary>
        internal static string lgPCBconfig {
            get {
                return ResourceManager.GetString("lgPCBconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string lgPower {
            get {
                return ResourceManager.GetString("lgPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        internal static string lgPressure {
            get {
                return ResourceManager.GetString("lgPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string lgProduct {
            get {
                return ResourceManager.GetString("lgProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string lgProductName {
            get {
                return ResourceManager.GetString("lgProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string lgProducts {
            get {
                return ResourceManager.GetString("lgProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string lgQuantity {
            get {
                return ResourceManager.GetString("lgQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Applied.
        /// </summary>
        internal static string lgQuantityApplied {
            get {
                return ResourceManager.GetString("lgQuantityApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Measured.
        /// </summary>
        internal static string lgQuantityMeasured {
            get {
                return ResourceManager.GetString("lgQuantityMeasured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string lgRate {
            get {
                return ResourceManager.GetString("lgRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Down.
        /// </summary>
        internal static string lgRateDown {
            get {
                return ResourceManager.GetString("lgRateDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Method.
        /// </summary>
        internal static string lgRateMethod {
            get {
                return ResourceManager.GetString("lgRateMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Up.
        /// </summary>
        internal static string lgRateUp {
            get {
                return ResourceManager.GetString("lgRateUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected Module.
        /// </summary>
        internal static string lgRealNano {
            get {
                return ResourceManager.GetString("lgRealNano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceivePort.
        /// </summary>
        internal static string lgReceivePort {
            get {
                return ResourceManager.GetString("lgReceivePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relay.
        /// </summary>
        internal static string lgRelay {
            get {
                return ResourceManager.GetString("lgRelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relays.
        /// </summary>
        internal static string lgRelays {
            get {
                return ResourceManager.GetString("lgRelays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan.
        /// </summary>
        internal static string lgRescan {
            get {
                return ResourceManager.GetString("lgRescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string lgResetStart {
            get {
                return ResourceManager.GetString("lgResetStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Rate.
        /// </summary>
        internal static string lgResponerate {
            get {
                return ResourceManager.GetString("lgResponerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPM.
        /// </summary>
        internal static string lgRPM {
            get {
                return ResourceManager.GetString("lgRPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save  .
        /// </summary>
        internal static string lgSave {
            get {
                return ResourceManager.GetString("lgSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string lgSaveAs {
            get {
                return ResourceManager.GetString("lgSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections.
        /// </summary>
        internal static string lgSection {
            get {
                return ResourceManager.GetString("lgSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section #.
        /// </summary>
        internal static string lgSectionNum {
            get {
                return ResourceManager.GetString("lgSectionNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections for this Product.
        /// </summary>
        internal static string lgSections {
            get {
                return ResourceManager.GetString("lgSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Port.
        /// </summary>
        internal static string lgSendPort {
            get {
                return ResourceManager.GetString("lgSendPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Time.
        /// </summary>
        internal static string lgSendTime {
            get {
                return ResourceManager.GetString("lgSendTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor.
        /// </summary>
        internal static string lgSensor {
            get {
                return ResourceManager.GetString("lgSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Counts/Unit.
        /// </summary>
        internal static string lgSensorCounts {
            get {
                return ResourceManager.GetString("lgSensorCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor ID.
        /// </summary>
        internal static string lgSensorID {
            get {
                return ResourceManager.GetString("lgSensorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Sensor Location.
        /// </summary>
        internal static string lgSensorLocation {
            get {
                return ResourceManager.GetString("lgSensorLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Counts.
        /// </summary>
        internal static string lgSensorTotalCounts {
            get {
                return ResourceManager.GetString("lgSensorTotalCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Pressure.
        /// </summary>
        internal static string lgShowPressure {
            get {
                return ResourceManager.GetString("lgShowPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation.
        /// </summary>
        internal static string lgSimulate {
            get {
                return ResourceManager.GetString("lgSimulate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string lgSimulationOff {
            get {
                return ResourceManager.GetString("lgSimulationOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slave.
        /// </summary>
        internal static string lgSlave {
            get {
                return ResourceManager.GetString("lgSlave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string lgSpeed {
            get {
                return ResourceManager.GetString("lgSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string lgStandard {
            get {
                return ResourceManager.GetString("lgStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string lgStart {
            get {
                return ResourceManager.GetString("lgStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank Starting Quantity.
        /// </summary>
        internal static string lgStartQuantity {
            get {
                return ResourceManager.GetString("lgStartQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string lgStop {
            get {
                return ResourceManager.GetString("lgStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        internal static string lgSwitch {
            get {
                return ResourceManager.GetString("lgSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank.
        /// </summary>
        internal static string lgTank {
            get {
                return ResourceManager.GetString("lgTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Left.
        /// </summary>
        internal static string lgTank_Remaining {
            get {
                return ResourceManager.GetString("lgTank_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank Size.
        /// </summary>
        internal static string lgTankSize {
            get {
                return ResourceManager.GetString("lgTankSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Rate ....
        /// </summary>
        internal static string lgTargetRate {
            get {
                return ResourceManager.GetString("lgTargetRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Rate Alt ....
        /// </summary>
        internal static string lgTargetRateAlt {
            get {
                return ResourceManager.GetString("lgTargetRateAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string lgTime {
            get {
                return ResourceManager.GetString("lgTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed Adjustment.
        /// </summary>
        internal static string lgTimedAjustment {
            get {
                return ResourceManager.GetString("lgTimedAjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Time / pulse (&lt;50 ms/pulse).
        /// </summary>
        internal static string lgTimeForMulti {
            get {
                return ResourceManager.GetString("lgTimeForMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time for one pulse (&gt;50 ms/pulse).
        /// </summary>
        internal static string lgTimeForSingle {
            get {
                return ResourceManager.GetString("lgTimeForSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string lgType {
            get {
                return ResourceManager.GetString("lgType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units/Volt.
        /// </summary>
        internal static string lgUnitsVolt {
            get {
                return ResourceManager.GetString("lgUnitsVolt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string lgUpdate {
            get {
                return ResourceManager.GetString("lgUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPM Applied.
        /// </summary>
        internal static string lgUPMApplied {
            get {
                return ResourceManager.GetString("lgUPMApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error %.
        /// </summary>
        internal static string lgUPMerror {
            get {
                return ResourceManager.GetString("lgUPMerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPM/PWM.
        /// </summary>
        internal static string lgUPMPWM {
            get {
                return ResourceManager.GetString("lgUPMPWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPM Target.
        /// </summary>
        internal static string lgUPMTarget {
            get {
                return ResourceManager.GetString("lgUPMTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Rate.
        /// </summary>
        internal static string lgVariableRate {
            get {
                return ResourceManager.GetString("lgVariableRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string lgVersion {
            get {
                return ResourceManager.GetString("lgVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Date.
        /// </summary>
        internal static string lgVersionDate {
            get {
                return ResourceManager.GetString("lgVersionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Module.
        /// </summary>
        internal static string lgVirtualNano {
            get {
                return ResourceManager.GetString("lgVirtualNano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait Time.
        /// </summary>
        internal static string lgWaitTime {
            get {
                return ResourceManager.GetString("lgWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string lgWidth {
            get {
                return ResourceManager.GetString("lgWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless Network.
        /// </summary>
        internal static string lgWirelessNetwork {
            get {
                return ResourceManager.GetString("lgWirelessNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Width (FT).
        /// </summary>
        internal static string lgWorkingWidthFT {
            get {
                return ResourceManager.GetString("lgWorkingWidthFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Width (M).
        /// </summary>
        internal static string lgWorkingWidthM {
            get {
                return ResourceManager.GetString("lgWorkingWidthM", resourceCulture);
            }
        }
    }
}
